development:
  adapter: mysql2
  database: hwinv
  pool: 5
  timeout: 5000
  host: localhost
  username: hwinv
  password: JV63bdy6GAxvrD3S

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: hwinv
  pool: 5
  timeout: 5000
  host: 37.205.10.125
  username: hwinv
  password: JV63bdy6GAxvrD3S
