require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RackUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # RackUnit. As you add validations to RackUnit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RackUnitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rack_units as @rack_units" do
      rack_unit = RackUnit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rack_units).should eq([rack_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested rack_unit as @rack_unit" do
      rack_unit = RackUnit.create! valid_attributes
      get :show, {:id => rack_unit.to_param}, valid_session
      assigns(:rack_unit).should eq(rack_unit)
    end
  end

  describe "GET new" do
    it "assigns a new rack_unit as @rack_unit" do
      get :new, {}, valid_session
      assigns(:rack_unit).should be_a_new(RackUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested rack_unit as @rack_unit" do
      rack_unit = RackUnit.create! valid_attributes
      get :edit, {:id => rack_unit.to_param}, valid_session
      assigns(:rack_unit).should eq(rack_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RackUnit" do
        expect {
          post :create, {:rack_unit => valid_attributes}, valid_session
        }.to change(RackUnit, :count).by(1)
      end

      it "assigns a newly created rack_unit as @rack_unit" do
        post :create, {:rack_unit => valid_attributes}, valid_session
        assigns(:rack_unit).should be_a(RackUnit)
        assigns(:rack_unit).should be_persisted
      end

      it "redirects to the created rack_unit" do
        post :create, {:rack_unit => valid_attributes}, valid_session
        response.should redirect_to(RackUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rack_unit as @rack_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        RackUnit.any_instance.stub(:save).and_return(false)
        post :create, {:rack_unit => {}}, valid_session
        assigns(:rack_unit).should be_a_new(RackUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RackUnit.any_instance.stub(:save).and_return(false)
        post :create, {:rack_unit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rack_unit" do
        rack_unit = RackUnit.create! valid_attributes
        # Assuming there are no other rack_units in the database, this
        # specifies that the RackUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RackUnit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rack_unit.to_param, :rack_unit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rack_unit as @rack_unit" do
        rack_unit = RackUnit.create! valid_attributes
        put :update, {:id => rack_unit.to_param, :rack_unit => valid_attributes}, valid_session
        assigns(:rack_unit).should eq(rack_unit)
      end

      it "redirects to the rack_unit" do
        rack_unit = RackUnit.create! valid_attributes
        put :update, {:id => rack_unit.to_param, :rack_unit => valid_attributes}, valid_session
        response.should redirect_to(rack_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the rack_unit as @rack_unit" do
        rack_unit = RackUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RackUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => rack_unit.to_param, :rack_unit => {}}, valid_session
        assigns(:rack_unit).should eq(rack_unit)
      end

      it "re-renders the 'edit' template" do
        rack_unit = RackUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RackUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => rack_unit.to_param, :rack_unit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rack_unit" do
      rack_unit = RackUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => rack_unit.to_param}, valid_session
      }.to change(RackUnit, :count).by(-1)
    end

    it "redirects to the rack_units list" do
      rack_unit = RackUnit.create! valid_attributes
      delete :destroy, {:id => rack_unit.to_param}, valid_session
      response.should redirect_to(rack_units_url)
    end
  end

end
